[package]
name = "error-trace"
version = "1.0.0"
edition = "2021"
authors = [ "Lut99" ]
description = "Small Rust crate for printing nice errors traits based on [`Error::source()`]."
repository = "https://github.com/Lut99/error-trace-rs"


[dependencies]
console = { version = "0.15", optional = true }


[features]
colors  = [ "colours" ]
colours = [ "colors", "dep:console" ]
