[package]
name = "error-trace"
version = "1.1.1"
edition = "2021"
authors = [ "Lut99" ]
description = "Small Rust crate for printing nice errors traits based on [`Error::source()`]."
repository = "https://github.com/Lut99/error-trace-rs"


[dependencies]
console = { version = "0.15", optional = true }


[features]
default = [ "macros" ]
colors  = [ "colours" ]
colours = [ "colors", "dep:console" ]
macros = []
